apiVersion: v1
kind: Service
metadata:
  name: ai-api-external
  namespace: {{ .Values.llmApi.namespace }}
  labels:
    {{- include "connectivity-link.labels" . | nindent 4 }}
  annotations:
    {{- include "connectivity-link.config-syncwave" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ .Values.llmApi.host }}
