apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.llmApi.namespace }}
  annotations:
    {{- include "connectivity-link.namespace-syncwave" . | nindent 4 }}
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
