nameOverride: "devspaces"
fullnameOverride: ""

namespace: ""

aiAssistantModel: qwen3-235b

devEnvironments:
  startTimeoutSeconds: 300
  secondsOfRunBeforeIdling: -1
  secondsOfInactivityBeforeIdling: -1
  maxNumberOfWorkspacesPerUser: 5
  maxNumberOfRunningWorkspacesPerUser: 5
  defaultEditor: che-incubator/che-code/latest
  storage:
    pvc:
      pvcStrategy: per-workspace
  resources:
    limits:
      memory: 6Gi
      cpu: "4"
    requests:
      memory: 512Mi
      cpu: 500m

openVSXURL: "https://open-vsx.org"

gitlab:
  host: ""

argocd:
  enabled: true
  instance:
    syncwave: "0"
