namespace: kuadrant-system

subscription:
  channel: stable
  installPlanApproval: Manual
  startingCSV: rhcl-operator.v1.4.2
  name: rhcl-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace

argocd:
  syncwave:
    enabled: true
    namespace: "-1"
    operatorgroup: "0"
    subscription: "0"
    instance: "2"
