apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: camel-credentials
  namespace: {{ include "user-workload.namespace" . }}
  labels:
    {{- include "user-workload.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  data:
    - secretKey: matrixToken
      remoteRef:
        key: secrets/tenants/{{ .Values.tenant.username }}/matrix
        property: token
    - secretKey: matrixRoom
      remoteRef:
        key: secrets/tenants/{{ .Values.tenant.username }}/matrix
        property: room
    - secretKey: rcToken
      remoteRef:
        key: secrets/tenants/{{ .Values.tenant.username }}/rocketchat
        property: token
    - secretKey: rcUserId
      remoteRef:
        key: secrets/tenants/{{ .Values.tenant.username }}/rocketchat
        property: userId
    - secretKey: rcChannel
      remoteRef:
        key: secrets/tenants/{{ .Values.tenant.username }}/rocketchat
        property: channel
  target:
    name: camel-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        MATRIX_SYNAPSE_URL: "http://synapse.{{ .Values.matrix.namespace }}.svc:8008"
        ROCKETCHAT_URL: "http://rocketchat.{{ .Values.rocketchat.namespace }}.svc:3000"
        MATRIX_TOKEN: "{{ "{{ .matrixToken }}" }}"
        MATRIX_ROOM: "{{ "{{ .matrixRoom }}" }}"
        ROCKETCHAT_TOKEN: "{{ "{{ .rcToken }}" }}"
        ROCKETCHAT_USERID: "{{ "{{ .rcUserId }}" }}"
        ROCKETCHAT_CHANNEL: "{{ "{{ .rcChannel }}" }}"
