apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka.clusterName }}
  namespace: {{ include "user-workload.namespace" . }}
  labels:
    {{- include "user-workload.labels" . | nindent 4 }}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
    {{- include "user-workload.kafka-syncwave" . | nindent 4 }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  kafka:
    version: {{ .Values.kafka.version }}
    metadataVersion: {{ .Values.kafka.metadataVersion }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: {{ .Values.kafka.config.offsetsTopicReplicationFactor }}
      transaction.state.log.replication.factor: {{ .Values.kafka.config.transactionStateLogReplicationFactor }}
      transaction.state.log.min.isr: {{ .Values.kafka.config.transactionStateLogMinIsr }}
      default.replication.factor: {{ .Values.kafka.config.defaultReplicationFactor }}
      min.insync.replicas: {{ .Values.kafka.config.minInsyncReplicas }}
  entityOperator: {}
