apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: {{ include "user-workload.namespace" . }}
  labels:
    strimzi.io/cluster: {{ .Values.kafka.clusterName }}
    {{- include "user-workload.labels" . | nindent 4 }}
  annotations:
    {{- include "user-workload.kafka-syncwave" . | nindent 4 }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  replicas: {{ .Values.kafka.dualRole.replicas }}
  roles:
    - controller
    - broker
  storage:
    type: ephemeral
  resources:
    requests:
      memory: {{ .Values.kafka.dualRole.resources.memory }}
      cpu: {{ .Values.kafka.dualRole.resources.cpu }}
    limits:
      memory: {{ .Values.kafka.dualRole.resources.memory }}
      cpu: {{ .Values.kafka.dualRole.resources.cpu }}
