apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lab-credentials
  namespace: {{ include "user-workload.namespace" . }}
  labels:
    {{- include "user-workload.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  data:
    - secretKey: s3AccessKey
      remoteRef:
        key: secrets/s3/noobaa
        property: accessKey
    - secretKey: s3SecretKey
      remoteRef:
        key: secrets/s3/noobaa
        property: secretKey
    - secretKey: s3Endpoint
      remoteRef:
        key: secrets/s3/noobaa
        property: endpoint
    - secretKey: matrixToken
      remoteRef:
        key: secrets/tenants/{{ .Values.tenant.username }}/matrix
        property: token
    - secretKey: matrixRoom
      remoteRef:
        key: secrets/tenants/{{ .Values.tenant.username }}/matrix
        property: room
    - secretKey: rcUserId
      remoteRef:
        key: secrets/tenants/{{ .Values.tenant.username }}/rocketchat
        property: userId
    - secretKey: rcToken
      remoteRef:
        key: secrets/tenants/{{ .Values.tenant.username }}/rocketchat
        property: token
    - secretKey: rcChannel
      remoteRef:
        key: secrets/tenants/{{ .Values.tenant.username }}/rocketchat
        property: channel
    - secretKey: hdGroupId
      remoteRef:
        key: secrets/tenants/{{ .Values.tenant.username }}/helpdesk
        property: groupId
    - secretKey: hdTypeIdIssue
      remoteRef:
        key: secrets/tenants/{{ .Values.tenant.username }}/helpdesk
        property: typeIdIssue
    - secretKey: hdPriorityIdNormal
      remoteRef:
        key: secrets/tenants/{{ .Values.tenant.username }}/helpdesk
        property: priorityIdNormal
    - secretKey: hdUsername
      remoteRef:
        key: secrets/tenants/{{ .Values.tenant.username }}/helpdesk
        property: username
    - secretKey: hdPassword
      remoteRef:
        key: secrets/tenants/{{ .Values.tenant.username }}/helpdesk
        property: password
  target:
    name: lab-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        database.json: |
          {
            "username": "{{ .Values.tenant.username }}",
            "password": "{{ .Values.tenant.password }}",
            "host": "postgres.{{ .Values.sharedDatabase.namespace }}.svc.cluster.local",
            "port": "5432",
            "database": "{{ .Values.sharedDatabase.database }}",
            "schema": "{{ .Values.tenant.username }}"
          }
        openshift.json: |
          {
            "password": "{{ .Values.tenant.password }}"
          }
        s3.json: |
          {
            "accessKey": "{{ "{{ .s3AccessKey }}" }}",
            "secretKey": "{{ "{{ .s3SecretKey }}" }}",
            "endpoint": "{{ "{{ .s3Endpoint }}" }}",
            "bucket": "{{ .Values.tenant.username }}"
          }
        matrix.json: |
          {
            "token": "{{ "{{ .matrixToken }}" }}",
            "room": "{{ "{{ .matrixRoom }}" }}"
          }
        rocketchat.json: |
          {
            "userId": "{{ "{{ .rcUserId }}" }}",
            "token": "{{ "{{ .rcToken }}" }}",
            "channel": "{{ "{{ .rcChannel }}" }}"
          }
        helpdesk.json: |
          {
            "groupId": "{{ "{{ .hdGroupId }}" }}",
            "typeIdIssue": "{{ "{{ .hdTypeIdIssue }}" }}",
            "priorityIdNormal": "{{ "{{ .hdPriorityIdNormal }}" }}",
            "username": "{{ "{{ .hdUsername }}" }}",
            "password": "{{ "{{ .hdPassword }}" }}"
          }
