gatewayClass:
  name: openshift-default
  controllerName: openshift.io/gateway-controller/v1

aiGateway:
  namespace: ai-gateway

llmApi:
  namespace: llm-api
  host: ""

argocd:
  syncwave:
    enabled: true
    namespace: "-1"
    gatewayclass: "0"
    config: "0"
    workloads: "1"
