{{- if .Values.sharedDatabase.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
{{ include "app-of-apps.metadata" (dict "name" .Values.sharedDatabase.name "namespace" .Values.argocd.namespace "syncWave" "1") }}
spec:
  destination:
    namespace: {{ .Values.sharedDatabase.namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster/module3/shared-database
    repoURL: {{ .Values.gitops.repoURL }}
    targetRevision: {{ .Values.gitops.targetRevision }}
    helm:
      valuesObject:
        namespace: {{ .Values.sharedDatabase.namespace }}
        admin:
          namespace: {{ .Values.admin.namespace }}
{{ include "app-of-apps.syncPolicy" . | indent 2 }}
{{- end }}
