---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: "{{ include "openshift-pipelines.name" . }}-operatorgroup"
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ include "openshift-pipelines.name" . }}-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: {{ .Values.subscription.channel }}
  installPlanApproval: {{ .Values.subscription.installPlanApproval }}
  name: {{ .Values.subscription.name }}
  source: {{ .Values.subscription.source }}
  sourceNamespace: {{ .Values.subscription.sourceNamespace }}
  {{- if .Values.subscription.startingCSV }}
  startingCSV: {{ .Values.subscription.startingCSV }}
  {{- end }}