apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
  namespace: {{ .Values.namespace }}
  annotations:
    {{- include "rocketchat.database-syncwave" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.storage.configdb.size }}
