apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: helpdesk-admin
  namespace: {{ .Values.namespace }}
  annotations:
    {{- include "helpdesk.config-syncwave" . | nindent 4 }}
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
