apiVersion: v1
kind: Service
metadata:
  name: helpdesk-db
  namespace: {{ .Values.namespace }}
  labels:
    app: helpdesk-db
  annotations:
    {{- include "helpdesk.database-syncwave" . | nindent 4 }}
spec:
  ports:
  - name: mongo
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: helpdesk-db
  type: ClusterIP
