apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    {{- include "kuadrant-operator.labels" . | nindent 4 }}
  annotations:
    {{- include "kuadrant-operator.namespace-syncwave" . | nindent 4 }}
