apiVersion: v1
kind: ConfigMap
metadata:
  name: vscode-editor-configurations
  namespace: {{ include "module5.namespace" . }}
  labels:
    {{- include "module5.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspaces-config
  annotations:
    {{- include "module5.workspace-syncwave" . | nindent 4 }}
data:
  settings.json: |
    {
      "security.workspace.trust.enabled": false,
      "security.workspace.trust.extensions": "trusted",
      "security.workspace.trust.trustedExtensions": [
        "redhat.mta-vscode-extension",
        "redhat.mta-core",
        "redhat.mta-java",
        "redhat.mta-csharp",
        "redhat.mta-go",
        "redhat.mta-javascript"
      ],
      "java.server.launchMode": "Standard",
      "java.import.maven.enabled": true,
      "java.import.maven.autoDetect": true,
      "redhat.telemetry.enabled": true,
      "workbench.colorTheme": "Default Light Modern"
    }
  extensions.json: |
    {
      "recommendations": [
        "redhat.mta-vscode-extension",
        "redhat.mta-core",
        "redhat.mta-java",
        "redhat.mta-csharp",
        "redhat.mta-go",
        "redhat.mta-javascript"
      ]
    }
