apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: workspace-credentials
  namespace: {{ include "module5.namespace" . }}
  labels:
    {{- include "module5.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    {{- include "module5.namespace-syncwave" . | nindent 4 }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  data:
    - secretKey: password
      remoteRef:
        key: secrets/common/password
        property: value
  target:
    name: workspace-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: che.eclipse.org
          app.kubernetes.io/component: workspaces-config
        annotations:
          controller.devfile.io/mount-as: env
      data:
        OCP_PASSWORD: "{{ "{{ .password }}" }}"
