{{- $prefix := include "parasol-insurance-tenant.prefix" . -}}
{{- $username := include "parasol-insurance-tenant.username" . -}}
{{- range $ns := list "build" "dev" "prod" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $prefix }}-monitoring-view
  namespace: {{ $prefix }}-{{ $ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-rules-view
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: {{ $username }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $prefix }}-monitoring-edit
  namespace: {{ $prefix }}-{{ $ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-edit
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: {{ $username }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $prefix }}-view
  namespace: {{ $prefix }}-{{ $ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: {{ $username }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $prefix }}-perses-edit
  namespace: {{ $prefix }}-{{ $ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: perses-cr
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: {{ $username }}
{{- end }}
