apiVersion: v1
kind: ServiceAccount
metadata:
  name: docs-proxy
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "showroom.labels" . | nindent 4 }}
  annotations:
    {{- include "showroom.config-syncwave" . | nindent 4 }}
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"docs"}}'
