apiVersion: v1
kind: Service
metadata:
  name: docs-proxy
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "showroom.labels" . | nindent 4 }}
  annotations:
    {{- include "showroom.config-syncwave" . | nindent 4 }}
    service.beta.openshift.io/serving-cert-secret-name: docs-proxy-tls
spec:
  selector:
    app: docs-proxy
  ports:
    - port: 8443
      targetPort: 8443
      name: proxy
