apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-image-puller
  namespace: openshift-config
  labels:
    {{- include "workspace-images.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-image-puller
  namespace: openshift-config
  labels:
    {{- include "workspace-images.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-image-puller
  namespace: openshift-config
  labels:
    {{- include "workspace-images.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
  - kind: ServiceAccount
    name: node-image-puller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: node-image-puller
---
apiVersion: v1
kind: Secret
metadata:
  name: internal-registry-token
  namespace: openshift-config
  labels:
    {{- include "workspace-images.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: "node-image-puller"
    argocd.argoproj.io/sync-wave: "1"
type: kubernetes.io/service-account-token
---
apiVersion: batch/v1
kind: Job
metadata:
  name: update-global-pull-secret
  namespace: openshift-config
  labels:
    {{- include "workspace-images.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  backoffLimit: 10
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: node-image-puller
      containers:
        - name: update-global-pull-secret
          image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
          command:
            - /bin/bash
            - -c
            - |
              set -e
              set -x
              cd /tmp
              oc get secret pull-secret -o jsonpath='{.data.\.dockerconfigjson}' | base64 -d > global-pull-secret.json
              oc registry login --registry="image-registry.openshift-image-registry.svc:5000" --auth-basic="<token>:$(oc get secret internal-registry-token -o jsonpath='{.data.token}' | base64 -d)" --to=global-pull-secret.json
              oc set data secret/pull-secret --from-file=.dockerconfigjson=./global-pull-secret.json
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
      securityContext:
        seccompProfile:
          type: RuntimeDefault
