kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cekit-builder-ist
  labels:
    {{- include "workspace-images.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - verbs:
      - get
      - watch
    apiGroups:
      - image.openshift.io
    resources:
      - imagestreamtags
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cekit-builder-ist
  labels:
    {{- include "workspace-images.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
  - kind: ServiceAccount
    name: cekit-builder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cekit-builder-ist