apiVersion: v1
kind: ServiceAccount
metadata:
  name: cekit-builder
  labels:
    {{- include "workspace-images.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cekit-image-builder
  labels:
    {{- include "workspace-images.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
- apiGroups:
    - build.openshift.io
  resources:
    - buildconfigs
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - build.openshift.io
  resources:
    - builds
    - buildconfigs/instantiate
  verbs:
    - create
    - get
    - list
    - watch
- apiGroups:
    - build.openshift.io
  resources:
    - builds
    - builds/log
    - builds/details
  verbs:
    - get
    - list
    - watch
    - update
- apiGroups:
    - image.openshift.io
  resources:
    - imagestreamtags
    - imagestreams
    - imagestreams/layers
  verbs:
    - get
    - watch
    - create
    - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cekit-image-builder
  labels:
    {{- include "workspace-images.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
  - kind: ServiceAccount
    name: cekit-builder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cekit-image-builder
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cekit-builder-pinned-image-sets
  labels:
    {{- include "workspace-images.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
- kind: ServiceAccount
  name: cekit-builder
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pinned-image-sets
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cekit-builder-podman
  labels:
    {{- include "workspace-images.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - cekit-podman-builder
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cekit-builder-podman
  labels:
    {{- include "workspace-images.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
  - kind: ServiceAccount
    name: cekit-builder
    namespace: {{ $.Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cekit-builder-podman

