apiVersion: batch/v1
kind: Job
metadata:
  name: dev-spaces-installplan-approve
  annotations:
    {{- include "devspaces-operator.argocd-syncwave" . | nindent 4 }}
spec:
  # ttlSecondsAfterFinished: 1200
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: dev-spaces-installplan-approver
      containers:
      - name: patch
        image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
        command:
          - /bin/bash
          - -c
          - |
            echo "Waiting for Dev Spaces InstallPlan to exist..."
            
            install_plan=""
            until [[ ${install_plan} != "" ]]
            do
              oc get installplan
              install_plan=$(oc get installplan | grep -E "devspaces|devworkspace" | grep false | cut -d" " -f1)
              sleep 15
            done
            oc patch installplan ${install_plan} --type merge --patch '{"spec":{"approved":true }}'
            echo "Dev Spaces InstallPlan Approved"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
