apiVersion: v1
kind: Service
metadata:
  name: element
  namespace: {{ .Values.namespace }}
  annotations:
    {{- include "matrix.workloads-syncwave" . | nindent 4 }}
spec:
  selector:
    app: element
  ports:
  - name: default
    protocol: TCP
    port: 80
    targetPort: 8080
