apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
  annotations:
    {{- include "shared-database.database-syncwave" . | nindent 4 }}
  labels:
    {{- include "shared-database.labels" . | nindent 4 }}
    app: postgres
spec:
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
