apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: {{ .Values.namespace }}
  annotations:
    {{- include "shared-database.database-syncwave" . | nindent 4 }}
  labels:
    {{- include "shared-database.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
